import { AutogeneratedRiskTables } from "./AutogeneratedRiskTables.mjs";
import { AutogeneratedTableLookup } from "./AutogeneratedTableLookup.mjs";
import { CCSMCommonFunctions } from "./CCSMCommonFunctions.mjs";
import { CDSConnectCommonsforFHIRv401 } from "./CDSConnectCommonsforFHIRv401.mjs";
import { DisplayCervicalCancerMedicalHistory } from "./DisplayCervicalCancerMedicalHistory.mjs";
import { FHIRHelpersv401 } from "./FHIRHelpers-4.0.1.mjs";
import { ManagementLibrary } from "./ManagementLibrary.mjs";
import { ScreeningAverageRiskLibrary } from "./ScreeningAverageRiskLibrary.mjs";
import { ScreeningDesExposureLibrary } from "./ScreeningDesExposureLibrary.mjs";
import { ScreeningImmunocompromisedLibrary } from "./ScreeningImmunocompromisedLibrary.mjs";
import { ScreeningSymptomaticLibrary } from "./ScreeningSymptomaticLibrary.mjs";
import { TopLevelScreeningLibrary } from "./TopLevelScreeningLibrary.mjs";

const elmJsonDependencyArray = [
  AutogeneratedRiskTables,
  AutogeneratedTableLookup,
  CCSMCommonFunctions,
  CDSConnectCommonsforFHIRv401,
  DisplayCervicalCancerMedicalHistory,
  FHIRHelpersv401,
  ManagementLibrary,
  ScreeningAverageRiskLibrary,
  ScreeningDesExposureLibrary,
  ScreeningImmunocompromisedLibrary,
  ScreeningSymptomaticLibrary,
  TopLevelScreeningLibrary
];

// Reformat ELM JSON value set references to match what is expected by the 
// code service built into the cql execution engine.
// NOTE: This is needed since we are not using `cql-exec-vsac`.
export const elmJsonDependencies = elmJsonDependencyArray.reduce((acc, elm) => {
  let refs = elm?.library?.valueSets?.def;
  if (refs) {
    refs = refs.map(r => {
      return {
        ...r,
        id: r.id.split('/').pop()
      }
    });
    elm.library.valueSets.def = refs;
  }
  return {
    ...acc,
    [elm.library.identifier.id]: elm
  }
}, {});